name: prisma_access_azure_select_subscription

label: Prisma Access Azure Select Subscription

description: Choose your Default Azure Subscription

type: python3

labels:
  collection:
    - Kitchen Sink

variables:
  - name: azure_account
    description: Azure Account to Use
    type_hint: dropdown
    default: ''
    source: azure_accounts
    help_text: These accounts were found when you logged in to Azure. Choose which account to use for deployment.

snippets:
  - name: script
    file: azure_select_subscription.py
    input_type: env
